FROM maven:3.6-jdk-8 as builder

ARG http_proxy
ARG https_proxy
ARG http_proxy_host
ARG http_proxy_port
ARG https_proxy_host
ARG https_proxy_port

WORKDIR /usr/src/mymaven

COPY . /usr/src/mymaven

#
# ここの扱いは要検討
#  /root/.m2配下を永続化しないと、とても遅くなる
#
RUN mkdir /root/.m2 \
&&  if [ -d "./.m2" ]; then \
        cp -r ./.m2/* /root/.m2/.; \
    fi

RUN echo "##################################################" \
&&  echo "# Unit Test" \
&&  echo "##################################################"
RUN /usr/local/bin/mvn-entrypoint.sh mvn -q test \
        -Dmaven.wagon.http.ssl.insecure=true \
        -Dmaven.wagon.http.ssl.allowall=true \
        -Dmaven.wagon.http.ssl.ignore.validity.dates=true \
        -Dhttp.proxyHost=$http_proxy_host \
        -Dhttp.proxyPort=$http_proxy_port \
        -Dhttps.proxyHost=$https_proxy_host \
        -Dhttps.proxyPort=$https_proxy_port

RUN echo "##################################################" \
&&  echo "# Unit Test Report" \
&&  echo "##################################################" \
&&  if [ -f "./target/site/jacoco/jacoco.csv" ]; then \
        cat ./target/site/jacoco/jacoco.csv; \
        echo "##################################################"; \
    fi

RUN echo "##################################################" \
&&  echo "# Make Jar file" \
&&  echo "##################################################"
RUN /usr/local/bin/mvn-entrypoint.sh \
        mvn -q -DskipTests package \
        -Dmaven.wagon.http.ssl.insecure=true \
        -Dmaven.wagon.http.ssl.allowall=true \
        -Dmaven.wagon.http.ssl.ignore.validity.dates=true \
        -Dhttp.proxyHost=$http_proxy_host \
        -Dhttp.proxyPort=$http_proxy_port \
        -Dhttps.proxyHost=$https_proxy_host \
        -Dhttps.proxyPort=$https_proxy_port

FROM java:openjdk-8-alpine

WORKDIR /usr/src/app
COPY --from=builder  /usr/src/mymaven/target/*.jar ./app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/urandom","-jar","./app.jar", "--port=80"]
